plugins {
    id 'org.springframework.boot' version '3.4.5' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'org.ec4j.editorconfig' version '0.1.0'
}

ext {
    querydslVersion = '5.0.0'
    mapstructVersion = '1.5.5.Final'
}

allprojects {
    group = 'com'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.32'
        annotationProcessor 'org.projectlombok:lombok:1.18.32'
        testCompileOnly 'org.projectlombok:lombok:1.18.32'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
        annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
        annotationProcessor 'jakarta.persistence:jakarta.persistence-api:3.1.0'
        annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.security:spring-security-test'
        testImplementation 'org.springframework.boot:spring-boot-testcontainers'
        testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'
        testImplementation 'org.testcontainers:testcontainers:1.19.3'
        testImplementation 'org.testcontainers:junit-jupiter:1.19.3'
        testImplementation 'com.redis:testcontainers-redis:2.2.2'
        testImplementation 'org.awaitility:awaitility:4.2.0'
        testImplementation 'com.h2database:h2'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(JavaCompile).configureEach {
        options.generatedSourceOutputDirectory = file("${layout.buildDirectory.get()}/generated/sources/annotationProcessor/java/main")
        options.compilerArgs += ['-parameters']
        options.incremental = false
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

editorconfig {
    includes = [
        'eventitta-app/**',
        'eventitta-api/**',
        'eventitta-domain/**',
        'eventitta-infra/**',
        'build.gradle',
        'settings.gradle'
    ]
    excludes = ['**/generated/**', '**/build/**']
}
